# -*- coding: utf-8 -*-
"""loja.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bqcFe4H69tuMOchu-FRsIjtbscISaoL1
"""

lista = []
lista.append([1,"placa de video",1000])
lista.append([2,"placa de video gtx",2000])

for item in lista:
  if item[0] == 1:
    lista.remove(item)
  print("-----------")
  print(item[0])
  print(item[1])
  print(item[2])

'''
novo_pedido
incrementa a variavel numero do pedido
incrementa o tempo de espera em minutos por ex. 20 minutos
adiciona a lista pedidos

get_tempo_espera
retorna o tempo de espera

pedido_entregue
recebe o numero do pedido
exclui o pedido da lista pedidos
inclui na lista pedidos entregues

get_pedidos
retorna os pedidos

get_pedidos_finalizados
retorna retorna a lista pedidos entregues

'''

from abc import ABC, abstractmethod

class loja(ABC):
  @abstractmethod
  def nome_loja(self):
    pass

  @abstractmethod
  def monta_catalogo(self):
    pass

class pedidos():
  def __init__(self):
    '''metodo construtor'''
    self.num_pedido = 0
    self.tempo_espera = 0
    self.valor_pedido = 0.0
    self.pedidos = [] # cod pedido[0] - cod item[1] - valor[2] - quantidade[3] - cliente[4]
    self.caixa = 0.0
    self.pedidos_entregues = []

  def novo_pedido(self, cod_item, valor, quantidade, cliente):
    self.num_pedido += 1
    self.tempo_espera += 20
    self.pedidos.append([self.num_pedido, cod_item, valor, quantidade, cliente])

  def get_tempo_espera(self):
    return self.tempo_espera

  def pedido_entregue(self, num_pedido):
    for pedido in self.pedidos:
      if pedido[0] == num_pedido:
        self.caixa += (pedido[2] * pedido[3])
        self.pedidos_entregues.append(pedido)
        self.pedidos.remove(pedido)
        self.tempo_espera -= 20

  def get_pedido(self):
    return self.pedidos

  def get_pedidos_finalizados(self):
    return self.pedidos_entregues

class minha_loja(loja):
  def __init__(self):
    self.nome = ''
    self.catalogo = []
    self.pedidos = pedidos()

  def nome_loja(self, nome):
    self.nome = nome

  def monta_catalogo(self, item):
    self.catalogo.append(item)

  def atendimento(self):
    print("Boa noite, Bem vindo a " + self.nome)
    cliente = input("Digite seu nome")
    print("")
    print(cliente + " ,Escolha seu produto")
    print("######## Menu #########")
    for itens in self.catalogo:
      print("Cod.: " + str(itens[0]))
      print("Desc.: " + str(itens[1]))
      print("Preço.: R$" + str(itens[2]))
      print("--------------------")

    cod_item = int(input("Digite o produto escolhido"))
    quantidade = int(input("Digite a quantidade escolhida"))
    for itens in self.catalogo:
      if itens[0] == cod_item:
        self.pedidos.novo_pedido(itens[0],itens[2],quantidade,cliente)
        print("Pedido realizado com sucesso, o tempo de entrega é " + str(self.pedidos.get_tempo_espera()) + "Minutos")

  def get_catalogo(self):
    print("-----------------")
    print("######### itens #########")
    for itens in self.catalogo:
      print("Cod.: " + str(itens[0]))
      print("Desc.: " + str(itens[1]))
      print("Preço.: R$" + str(itens[2]))
      print("--------------------")

  def lista_pedidos(self):
    pedidos = self.pedidos.get_pedido()
    for ped in pedidos:
      print("numero do pedido " + str(ped[0]))
      print("item " + str(ped[1]))
      print("Valor R$" + str(ped[2]))
      print("Qtd. " + str(ped[3]))
      print("cliente " + str(ped[4]))

  def finalizar_pedido(self):
    num_ped = int(input("Digite o numero do pedido que será entregue"))
    self.pedidos.pedido_entregue(num_ped)

  def relatorio_caixa(self):
    valor_total = 0
    pedidos_fechados = self.pedidos.get_pedidos_finalizados()
    print("Relatorio de caixa")
    print("------------------")
    for rel in pedidos_fechados:
      valor_total += (rel[2] * rel[3])
      print("Numero pedido: " + str(rel[0]))
      print("item: " + str(rel[1]))
      print("valor: R$" + str(rel[2]))
      print("qtd.: " + str(rel[3]))
      print("cliente: " + str(rel[4]))
      print("Valor Total: R$" + str(rel[2] * rel[3]))
      print("------------------")
    print("Valor total do caixa: R$" + str(valor_total))

loja = minha_loja()

loja.nome_loja("Casa dos Eletronicos")

loja.monta_catalogo([1,"Placa de Video", 1000])
loja.monta_catalogo([2,"Notebook", 3000])
loja.monta_catalogo([3,"HD", 300])

loja.get_catalogo()

loja.atendimento()

loja.lista_pedidos()

loja.finalizar_pedido()

loja.relatorio_caixa()